version: '3.7'

services:
  postgres:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_user:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user_db_username
      - POSTGRES_PASSWORD=user_db_password
      - POSTGRES_DB=user_db_dev

  user_service:
    build: ./user-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./user-service/:/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URI=postgresql://user_db_username:user_db_password@postgres/user_db_dev
    depends_on:
      - postgres

  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - "27017"
    volumes:
      - mongodb_data_schedules:/bitnami/mongodb

  schedules_service:
    build: ./schedules-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./schedules-service/:/app/
    ports:
      - 8001:8000
    environment:
      - MONGO_URI=mongodb://mongodb:27017/schedules
      - DB_NAME=schedules
    depends_on:
      - mongodb

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user_service
      - schedules_service

volumes:
  postgres_data_user:
  mongodb_data_schedules:
